### ISSUE TITLE
How do you run vulture in Linux?

### ISSUE THREAD

**Issue by Maxwell101** [didiercrunch/vulture#1]

**Comment by didiercrunch** [comment]
Indeed, the binary file is a zip file that contains a directory.  In the directory there is a binary called `vulture`.  Consequently, you can `cd` into the directory and starts vulture from there by the command `./vulture`.

In short, I'll assume you run on ubuntu just open a terminal and type...

```
$ cd Download
$ tar -xvzf vulture_1.2.1-vulture_linux_amd64.tar.gz
$ cd vulture_1.2.1-vulture_linux_amd64
$ ./vulture
```

Note that it is important that you starts vulture from where the binary is because the html/css/js files to create the we interface are in the `static` directory next to it. 

cheers,
didier

**Comment by Maxwell101** [comment]
I have over 600,000 messages in my collection.  Will vulture be able to run queries on a collection that large?  For example, if I wanted to search for SEQNUM: 504444, how would I type that in the query box.  I’ve done this: db.messages.findOne( { SEQNUM : "504444" } ) but that doesn’t work.

**Comment by didiercrunch** [comment]
Yes that should work.  I presumed that I have used vulture on much larger collections.  But the results should be the same than what you would have with the default mongo client.  In your collection ui there is a "search bar" where you can put your queries.  It is a good place to understand.

In the specific case you flag, I presume your issue is that you should query for `{ SEQNUM :  504444 }` instead of `{ SEQNUM : "504444" }`.

cheers

**Comment by Maxwell101** [comment]
That worked.  Thanks for your help!

**Comment by didiercrunch** [comment]
always happy to help!

**Comment by Maxwell101** [comment]
Would you know how to search for just a keyword and not a string  in a collection?

**Comment by didiercrunch** [comment]
haha.

I presume you have a collection called `restaurants` and each document represent a `restaurant`. Each restaurent contains a field named `name`.  I presume you are looking for a restaurant which its name contains the word `truie`.

The most flexible but less effective way to search in text is via regular expression.  In your case, searching for `{name: /truie/gi}` should work and out put a restaurent like `chez ma grosse truie cherie`.

The thing `/truie/gi` is called a javascript regular expression.  It is made to search text in text.  You can learn more about it [here](http://www.w3schools.com/js/js_regexp.asp).

cheers

**Comment by Maxwell101** [comment]
Actually, what I have is a collection named messages.  The data comes from syslog-ng.  I just need to search the “messages” collection for single keywords like “authenticate”, “failed”, “info” etcetera.  I’m trying to search for just one keyword at a time.  Right now I’m using the mViewer front end.

 As of now the slash /pattern/ is not yet supported so I’ll need to use $regex with pattern within quotes syntax instead.
